"""empty message

Revision ID: 12d915fda806
Revises: 531e451b0ff4
Create Date: 2025-01-24 09:52:10.579031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d915fda806'
down_revision: Union[str, None] = '531e451b0ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('last_message_send_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'last_message_send_at')
    # ### end Alembic commands ###
