"""empty message

Revision ID: 43f56e921be7
Revises: f1ca7840e0bb
Create Date: 2025-02-07 09:01:36.282971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f56e921be7'
down_revision: Union[str, None] = 'f1ca7840e0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('edit_data', sa.JSON(), nullable=True))
    op.add_column('message', sa.Column('edit_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'edit_at')
    op.drop_column('message', 'edit_data')
    op.drop_column('message', 'delete_at')
    # ### end Alembic commands ###
