"""empty message

Revision ID: 531e451b0ff4
Revises: 80b865e76e69
Create Date: 2024-11-07 14:39:22.564892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531e451b0ff4'
down_revision: Union[str, None] = '80b865e76e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('icon_url', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('icon_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon_url')
    op.drop_column('chat', 'icon_url')
    # ### end Alembic commands ###
