"""empty message

Revision ID: cb2372751ce3
Revises: 57346cae55b7
Create Date: 2024-10-03 20:49:50.478418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2372751ce3'
down_revision: Union[str, None] = '57346cae55b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('is_archive', sa.Boolean(), nullable=False))
    op.alter_column('chat_users', 'last_read_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_users', 'last_read_message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('chat', 'is_archive')
    # ### end Alembic commands ###
