"""empty message

Revision ID: f1ca7840e0bb
Revises: 12d915fda806
Create Date: 2025-01-24 11:49:34.524482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ca7840e0bb'
down_revision: Union[str, None] = '12d915fda806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat', 'platform', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_column('chat', 'platform_id')
    # ### end Alembic commands ###
